const products=[
{id:1,name:"Sculpted Linen Shirt",cat:"Men",price:1499,old:1999,size:["S","M","L","XL"],color:"Ivory",img:"https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?auto=format&fit=crop&w=900&q=88",desc:"A relaxed linen shirt with a clean silhouette, designed for effortless everyday dressing."},
{id:2,name:"Satin Slip Dress",cat:"Women",price:2199,old:2999,size:["XS","S","M","L"],color:"Rose",img:"https://images.unsplash.com/photo-1566174053879-31528523f8ae?auto=format&fit=crop&w=900&q=88",desc:"A fluid satin dress with a flattering neckline and understated evening elegance."},
{id:3,name:"Classic Denim Jacket",cat:"Men",price:1899,old:2499,size:["S","M","L","XL"],color:"Blue",img:"https://images.unsplash.com/photo-1495105787522-5334e3ffa0ef?auto=format&fit=crop&w=900&q=88",desc:"A versatile denim layer with a modern fit and timeless wash."},
{id:4,name:"Minimal Knit Top",cat:"Women",price:1299,old:1699,size:["XS","S","M","L"],color:"Cream",img:"https://images.unsplash.com/photo-1620799140408-edc6dcb6d633?auto=format&fit=crop&w=900&q=88",desc:"Soft-touch knitwear made for polished everyday outfits."},
{id:5,name:"Everyday Cargo Pants",cat:"Men",price:1699,old:2199,size:["S","M","L","XL"],color:"Olive",img:"https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=900&q=88",desc:"Utility-inspired trousers with a comfortable straight fit."},
{id:6,name:"Floral Midi Dress",cat:"Women",price:2399,old:3199,size:["XS","S","M","L"],color:"Floral",img:"https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?auto=format&fit=crop&w=900&q=88",desc:"A romantic printed midi with an easy day-to-evening silhouette."},
{id:7,name:"Kids Weekend Set",cat:"Kids",price:999,old:1299,size:["S","M","L"],color:"Peach",img:"https://images.unsplash.com/photo-1503919545889-aef636e10ad4?auto=format&fit=crop&w=900&q=88",desc:"A soft and playful co-ord set for weekends and adventures."},
{id:8,name:"Canvas Everyday Sneakers",cat:"Kids",price:1199,old:1499,size:["S","M","L"],color:"White",img:"https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?auto=format&fit=crop&w=900&q=88",desc:"Lightweight everyday sneakers with a clean canvas finish."}
];
function getCart(){return JSON.parse(localStorage.getItem('stylehubCart')||'[]')}
function saveCart(c){localStorage.setItem('stylehubCart',JSON.stringify(c));updateCount()}
function updateCount(){const n=getCart().reduce((a,b)=>a+b.qty,0);document.querySelectorAll('#cartCount').forEach(e=>e.textContent=n)}
function money(n){return '₹'+Number(n).toLocaleString('en-IN')}
function toast(msg){const t=document.createElement('div');t.className='toast';t.textContent=msg;document.body.appendChild(t);setTimeout(()=>t.remove(),2200)}
function addToCart(id,size='M',qty=1){const p=products.find(x=>x.id==id);if(!p)return;let c=getCart();let item=c.find(x=>x.id==id&&x.size==size);item?item.qty+=qty:c.push({id:p.id,qty,size});saveCart(c);toast(p.name+' added to cart')}
function getWishlist(){return JSON.parse(localStorage.getItem('stylehubWishlist')||'[]')}
function wishlist(id){let w=getWishlist();if(w.includes(id)){w=w.filter(x=>x!==id);toast('Removed from wishlist')}else{w.push(id);toast('Added to wishlist ♡')}localStorage.setItem('stylehubWishlist',JSON.stringify(w));renderWishlistButtons()}
function renderWishlistButtons(){const w=getWishlist();document.querySelectorAll('[data-heart]').forEach(b=>b.textContent=w.includes(Number(b.dataset.heart))?'♥':'♡')}
function productCard(p){return `<article class="product-card"><a href="product.html?id=${p.id}"><div class="product-image"><img loading="lazy" src="${p.img}" alt="${p.name}"><span class="badge">NEW</span><button class="heart" data-heart="${p.id}" onclick="event.preventDefault();wishlist(${p.id})">${getWishlist().includes(p.id)?'♥':'♡'}</button></div><div class="product-info"><h3>${p.name}</h3><p>${p.cat} • ${p.color}</p><span class="price">${money(p.price)} <span class="old">${money(p.old)}</span></span></div></a></article>`}
function renderHome(){const el=document.getElementById('homeProducts');if(el)el.innerHTML=products.slice(0,4).map(productCard).join('');renderWishlistButtons()}
function renderProducts(){const grid=document.getElementById('productsGrid');if(!grid)return;const cat=document.getElementById('categoryFilter').value,size=document.getElementById('sizeFilter').value,q=(document.getElementById('searchInput').value||'').toLowerCase(),sort=document.getElementById('sortFilter').value;let arr=products.filter(p=>(cat==='All'||p.cat===cat)&&(size==='All'||p.size.includes(size))&&(p.name.toLowerCase().includes(q)||p.cat.toLowerCase().includes(q)||p.color.toLowerCase().includes(q)));if(sort==='low')arr.sort((a,b)=>a.price-b.price);if(sort==='high')arr.sort((a,b)=>b.price-a.price);grid.innerHTML=arr.length?arr.map(productCard).join(''):`<div style="grid-column:1/-1;padding:80px 20px;text-align:center;color:#777"><h3 style="color:#171722">No styles found</h3><p>Try another search or remove a filter.</p></div>`;renderWishlistButtons()}
function initFilters(){const params=new URLSearchParams(location.search),cat=params.get('category');if(cat&&document.getElementById('categoryFilter'))document.getElementById('categoryFilter').value=cat;renderProducts()}
function renderDetail(){const el=document.getElementById('productDetail');if(!el)return;const id=Number(new URLSearchParams(location.search).get('id'))||1,p=products.find(x=>x.id===id)||products[0];document.title=p.name+' | StyleHub';el.innerHTML=`<div class="detail-image"><img src="${p.img}" alt="${p.name}"></div><div class="detail-copy"><p class="eyebrow">${p.cat.toUpperCase()} / NEW ARRIVAL</p><h1>${p.name}</h1><div class="price">${money(p.price)} <span class="old">${money(p.old)}</span></div><p>${p.desc}</p><div class="option"><div class="option-title">COLOR — ${p.color.toUpperCase()}</div><div class="sizes"><button class="size-btn selected">${p.color}</button></div></div><div class="option"><div class="option-title">SELECT SIZE</div><div class="sizes">${p.size.map(s=>`<button class="size-btn" onclick="selectSize(this)">${s}</button>`).join('')}</div></div><div class="option"><div class="option-title">QUANTITY</div><div class="qty"><button onclick="changeDetailQty(-1)">−</button><span id="detailQty">1</span><button onclick="changeDetailQty(1)">+</button></div></div><button class="btn btn-dark full-btn" onclick="detailAdd(${p.id})">Add to bag — ${money(p.price)}</button><a class="btn full-btn" href="cart.html">View bag</a><hr style="border:0;border-top:1px solid #eee;margin:30px 0"><p>✓ Free shipping over ₹999<br>✓ Easy 7-day returns<br>✓ Secure checkout</p></div>`}
function selectSize(btn){btn.parentElement.querySelectorAll('.size-btn').forEach(x=>x.classList.remove('selected'));btn.classList.add('selected')}
function changeDetailQty(n){const e=document.getElementById('detailQty');e.textContent=Math.max(1,Number(e.textContent)+n)}
function detailAdd(id){const size=[...document.querySelectorAll('.detail-copy .option')][1]?.querySelector('.selected')?.textContent||'M';const q=Number(document.getElementById('detailQty')?.textContent||1);addToCart(id,size,q)}
function renderCart(){const el=document.getElementById('cartPage');if(!el)return;const c=getCart();if(!c.length){el.innerHTML=`<div style="text-align:center;padding:80px 0"><p class="eyebrow">YOUR BAG</p><h2 style="font-family:'Playfair Display';font-size:40px">Nothing here yet.</h2><p style="color:#777">Discover something you love and make it yours.</p><a class="btn btn-dark" href="products.html">Start shopping →</a></div>`;return}let sub=0;const rows=c.map((x,i)=>{const p=products.find(a=>a.id===x.id);if(!p)return '';sub+=p.price*x.qty;return `<div class="cart-item"><img src="${p.img}" alt="${p.name}"><div><h3>${p.name}</h3><p>${p.cat} • ${p.color} • Size ${x.size}</p><div class="qty"><button onclick="cartQty(${i},-1)">−</button><span>${x.qty}</span><button onclick="cartQty(${i},1)">+</button></div></div><div class="price">${money(p.price*x.qty)}<br><button style="border:0;background:none;color:#999;cursor:pointer;margin-top:10px" onclick="removeCart(${i})">Remove</button></div></div>`}).join('');const ship=sub>=999?0:99;el.innerHTML=`<div>${rows}</div><aside class="summary"><h3>Order summary</h3><div class="sum-row"><span>Subtotal</span><span>${money(sub)}</span></div><div class="sum-row"><span>Shipping</span><span>${ship?money(ship):'FREE'}</span></div><div class="sum-row"><span>Discount</span><span>—</span></div><div class="sum-row total"><span>Total</span><span>${money(sub+ship)}</span></div><a class="btn btn-dark full-btn" href="checkout.html">Proceed to checkout</a><p style="font-size:10px;color:#777;text-align:center">🔒 Secure simulated checkout</p></aside>`}
function cartQty(i,n){let c=getCart();c[i].qty=Math.max(1,c[i].qty+n);saveCart(c);renderCart()}
function removeCart(i){let c=getCart();c.splice(i,1);saveCart(c);renderCart();toast('Item removed')}
function renderCheckout(){const el=document.getElementById('checkoutSummary');if(!el)return;const c=getCart();let sub=c.reduce((s,x)=>s+(products.find(p=>p.id===x.id)?.price||0)*x.qty,0),ship=sub>=999?0:99;el.innerHTML=`<h3>Order summary</h3>${c.map(x=>{let p=products.find(p=>p.id===x.id);return `<div class="sum-row"><span>${p.name} × ${x.qty}</span><span>${money(p.price*x.qty)}</span></div>`}).join('')}<div class="sum-row"><span>Shipping</span><span>${ship?'₹99':'FREE'}</span></div><div class="sum-row total"><span>Total</span><span>${money(sub+ship)}</span></div>`}
function placeOrder(e){e.preventDefault();if(!getCart().length){toast('Your bag is empty');return}localStorage.removeItem('stylehubCart');alert('Order placed successfully! 🎉\nThis is a simulated internship checkout.');location.href='index.html'}
function loginUser(e){if(e)e.preventDefault();localStorage.setItem('stylehubUser','1');toast('Welcome to StyleHub!');setTimeout(()=>location.href='account.html',500)}
function focusSearch(){if(location.pathname.includes('products'))document.getElementById('searchInput')?.focus();else location.href='products.html'}
function toggleMenu(){document.querySelector('.nav')?.classList.toggle('show')}
document.addEventListener('DOMContentLoaded',()=>{updateCount();renderHome();initFilters();renderDetail();renderCart();renderCheckout()});
